// Code generated by protoc-gen-go. DO NOT EDIT.
// source: SchedularService.proto

package SchedularService

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RowType int32

const (
	RowType_Editorial      RowType = 0
	RowType_Recommendation RowType = 1
	RowType_Dynamic        RowType = 2
)

var RowType_name = map[int32]string{
	0: "Editorial",
	1: "Recommendation",
	2: "Dynamic",
}

var RowType_value = map[string]int32{
	"Editorial":      0,
	"Recommendation": 1,
	"Dynamic":        2,
}

func (x RowType) String() string {
	return proto.EnumName(RowType_name, int32(x))
}

func (RowType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_199c4d2fc282de6a, []int{0}
}

type RowLayout int32

const (
	RowLayout_Landscape RowLayout = 0
	RowLayout_Portrait  RowLayout = 1
	RowLayout_Square    RowLayout = 3
	RowLayout_Circle    RowLayout = 4
)

var RowLayout_name = map[int32]string{
	0: "Landscape",
	1: "Portrait",
	3: "Square",
	4: "Circle",
}

var RowLayout_value = map[string]int32{
	"Landscape": 0,
	"Portrait":  1,
	"Square":    3,
	"Circle":    4,
}

func (x RowLayout) String() string {
	return proto.EnumName(RowLayout_name, int32(x))
}

func (RowLayout) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_199c4d2fc282de6a, []int{1}
}

type Schedule struct {
	Brand                string               `protobuf:"bytes,1,opt,name=brand,proto3" json:"brand,omitempty"`
	Vendor               string               `protobuf:"bytes,2,opt,name=vendor,proto3" json:"vendor,omitempty"`
	StartTime            int32                `protobuf:"varint,3,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime              int32                `protobuf:"varint,4,opt,name=endTime,proto3" json:"endTime,omitempty"`
	Pages                []*Page              `protobuf:"bytes,6,rep,name=pages,proto3" json:"pages,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,8,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-" bson:"-"`
	XXX_unrecognized     []byte               `json:"-" bson:"-"`
	XXX_sizecache        int32                `json:"-" bson:"-"`
}

func (m *Schedule) Reset()         { *m = Schedule{} }
func (m *Schedule) String() string { return proto.CompactTextString(m) }
func (*Schedule) ProtoMessage()    {}
func (*Schedule) Descriptor() ([]byte, []int) {
	return fileDescriptor_199c4d2fc282de6a, []int{0}
}

func (m *Schedule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Schedule.Unmarshal(m, b)
}
func (m *Schedule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Schedule.Marshal(b, m, deterministic)
}
func (m *Schedule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Schedule.Merge(m, src)
}
func (m *Schedule) XXX_Size() int {
	return xxx_messageInfo_Schedule.Size(m)
}
func (m *Schedule) XXX_DiscardUnknown() {
	xxx_messageInfo_Schedule.DiscardUnknown(m)
}

var xxx_messageInfo_Schedule proto.InternalMessageInfo

func (m *Schedule) GetBrand() string {
	if m != nil {
		return m.Brand
	}
	return ""
}

func (m *Schedule) GetVendor() string {
	if m != nil {
		return m.Vendor
	}
	return ""
}

func (m *Schedule) GetStartTime() int32 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *Schedule) GetEndTime() int32 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *Schedule) GetPages() []*Page {
	if m != nil {
		return m.Pages
	}
	return nil
}

func (m *Schedule) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Schedule) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type Page struct {
	PageName             string               `protobuf:"bytes,1,opt,name=pageName,proto3" json:"pageName,omitempty"`
	PageIndex            int32                `protobuf:"varint,2,opt,name=pageIndex,proto3" json:"pageIndex,omitempty"`
	PageLogo             string               `protobuf:"bytes,3,opt,name=pageLogo,proto3" json:"pageLogo,omitempty"`
	Row                  []*Row               `protobuf:"bytes,4,rep,name=row,proto3" json:"row,omitempty"`
	Carousel             []*Carousel          `protobuf:"bytes,5,rep,name=carousel,proto3" json:"carousel,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,7,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,8,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-" bson:"-"`
	XXX_unrecognized     []byte               `json:"-" bson:"-"`
	XXX_sizecache        int32                `json:"-" bson:"-"`
}

func (m *Page) Reset()         { *m = Page{} }
func (m *Page) String() string { return proto.CompactTextString(m) }
func (*Page) ProtoMessage()    {}
func (*Page) Descriptor() ([]byte, []int) {
	return fileDescriptor_199c4d2fc282de6a, []int{1}
}

func (m *Page) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Page.Unmarshal(m, b)
}
func (m *Page) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Page.Marshal(b, m, deterministic)
}
func (m *Page) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Page.Merge(m, src)
}
func (m *Page) XXX_Size() int {
	return xxx_messageInfo_Page.Size(m)
}
func (m *Page) XXX_DiscardUnknown() {
	xxx_messageInfo_Page.DiscardUnknown(m)
}

var xxx_messageInfo_Page proto.InternalMessageInfo

func (m *Page) GetPageName() string {
	if m != nil {
		return m.PageName
	}
	return ""
}

func (m *Page) GetPageIndex() int32 {
	if m != nil {
		return m.PageIndex
	}
	return 0
}

func (m *Page) GetPageLogo() string {
	if m != nil {
		return m.PageLogo
	}
	return ""
}

func (m *Page) GetRow() []*Row {
	if m != nil {
		return m.Row
	}
	return nil
}

func (m *Page) GetCarousel() []*Carousel {
	if m != nil {
		return m.Carousel
	}
	return nil
}

func (m *Page) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Page) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

type Carousel struct {
	Target               string   `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	PackageName          string   `protobuf:"bytes,2,opt,name=packageName,proto3" json:"packageName,omitempty"`
	ImageUrl             string   `protobuf:"bytes,3,opt,name=imageUrl,proto3" json:"imageUrl,omitempty"`
	Title                string   `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *Carousel) Reset()         { *m = Carousel{} }
func (m *Carousel) String() string { return proto.CompactTextString(m) }
func (*Carousel) ProtoMessage()    {}
func (*Carousel) Descriptor() ([]byte, []int) {
	return fileDescriptor_199c4d2fc282de6a, []int{2}
}

func (m *Carousel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Carousel.Unmarshal(m, b)
}
func (m *Carousel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Carousel.Marshal(b, m, deterministic)
}
func (m *Carousel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Carousel.Merge(m, src)
}
func (m *Carousel) XXX_Size() int {
	return xxx_messageInfo_Carousel.Size(m)
}
func (m *Carousel) XXX_DiscardUnknown() {
	xxx_messageInfo_Carousel.DiscardUnknown(m)
}

var xxx_messageInfo_Carousel proto.InternalMessageInfo

func (m *Carousel) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *Carousel) GetPackageName() string {
	if m != nil {
		return m.PackageName
	}
	return ""
}

func (m *Carousel) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

func (m *Carousel) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

// -1 for sort descending and 1 for sort ascending,
type Row struct {
	Rowlayout            RowLayout                  `protobuf:"varint,1,opt,name=rowlayout,proto3,enum=SchedularService.RowLayout" json:"rowlayout,omitempty"`
	RowName              string                     `protobuf:"bytes,2,opt,name=rowName,proto3" json:"rowName,omitempty"`
	RowIndex             int32                      `protobuf:"varint,3,opt,name=rowIndex,proto3" json:"rowIndex,omitempty"`
	RowFilters           map[string]*RowFilterValue `protobuf:"bytes,4,rep,name=rowFilters,proto3" json:"rowFilters,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	RowSort              map[string]int32           `protobuf:"bytes,5,rep,name=rowSort,proto3" json:"rowSort,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"zigzag32,2,opt,name=value,proto3"`
	RowTileIds           []string                   `protobuf:"bytes,6,rep,name=rowTileIds,proto3" json:"rowTileIds,omitempty"`
	RowType              RowType                    `protobuf:"varint,7,opt,name=rowType,proto3,enum=SchedularService.RowType" json:"rowType,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-" bson:"-"`
	XXX_unrecognized     []byte                     `json:"-" bson:"-"`
	XXX_sizecache        int32                      `json:"-" bson:"-"`
}

func (m *Row) Reset()         { *m = Row{} }
func (m *Row) String() string { return proto.CompactTextString(m) }
func (*Row) ProtoMessage()    {}
func (*Row) Descriptor() ([]byte, []int) {
	return fileDescriptor_199c4d2fc282de6a, []int{3}
}

func (m *Row) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Row.Unmarshal(m, b)
}
func (m *Row) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Row.Marshal(b, m, deterministic)
}
func (m *Row) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Row.Merge(m, src)
}
func (m *Row) XXX_Size() int {
	return xxx_messageInfo_Row.Size(m)
}
func (m *Row) XXX_DiscardUnknown() {
	xxx_messageInfo_Row.DiscardUnknown(m)
}

var xxx_messageInfo_Row proto.InternalMessageInfo

func (m *Row) GetRowlayout() RowLayout {
	if m != nil {
		return m.Rowlayout
	}
	return RowLayout_Landscape
}

func (m *Row) GetRowName() string {
	if m != nil {
		return m.RowName
	}
	return ""
}

func (m *Row) GetRowIndex() int32 {
	if m != nil {
		return m.RowIndex
	}
	return 0
}

func (m *Row) GetRowFilters() map[string]*RowFilterValue {
	if m != nil {
		return m.RowFilters
	}
	return nil
}

func (m *Row) GetRowSort() map[string]int32 {
	if m != nil {
		return m.RowSort
	}
	return nil
}

func (m *Row) GetRowTileIds() []string {
	if m != nil {
		return m.RowTileIds
	}
	return nil
}

func (m *Row) GetRowType() RowType {
	if m != nil {
		return m.RowType
	}
	return RowType_Editorial
}

type RowFilterValue struct {
	Values               []string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *RowFilterValue) Reset()         { *m = RowFilterValue{} }
func (m *RowFilterValue) String() string { return proto.CompactTextString(m) }
func (*RowFilterValue) ProtoMessage()    {}
func (*RowFilterValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_199c4d2fc282de6a, []int{4}
}

func (m *RowFilterValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RowFilterValue.Unmarshal(m, b)
}
func (m *RowFilterValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RowFilterValue.Marshal(b, m, deterministic)
}
func (m *RowFilterValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RowFilterValue.Merge(m, src)
}
func (m *RowFilterValue) XXX_Size() int {
	return xxx_messageInfo_RowFilterValue.Size(m)
}
func (m *RowFilterValue) XXX_DiscardUnknown() {
	xxx_messageInfo_RowFilterValue.DiscardUnknown(m)
}

var xxx_messageInfo_RowFilterValue proto.InternalMessageInfo

func (m *RowFilterValue) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

type GetScheduleRequest struct {
	Vendor               string   `protobuf:"bytes,1,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Brand                string   `protobuf:"bytes,2,opt,name=brand,proto3" json:"brand,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *GetScheduleRequest) Reset()         { *m = GetScheduleRequest{} }
func (m *GetScheduleRequest) String() string { return proto.CompactTextString(m) }
func (*GetScheduleRequest) ProtoMessage()    {}
func (*GetScheduleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_199c4d2fc282de6a, []int{5}
}

func (m *GetScheduleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetScheduleRequest.Unmarshal(m, b)
}
func (m *GetScheduleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetScheduleRequest.Marshal(b, m, deterministic)
}
func (m *GetScheduleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetScheduleRequest.Merge(m, src)
}
func (m *GetScheduleRequest) XXX_Size() int {
	return xxx_messageInfo_GetScheduleRequest.Size(m)
}
func (m *GetScheduleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetScheduleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetScheduleRequest proto.InternalMessageInfo

func (m *GetScheduleRequest) GetVendor() string {
	if m != nil {
		return m.Vendor
	}
	return ""
}

func (m *GetScheduleRequest) GetBrand() string {
	if m != nil {
		return m.Brand
	}
	return ""
}

type DeleteScheduleRequest struct {
	Vendor               string   `protobuf:"bytes,1,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Brand                string   `protobuf:"bytes,2,opt,name=brand,proto3" json:"brand,omitempty"`
	StartTime            int32    `protobuf:"varint,3,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime              int32    `protobuf:"varint,4,opt,name=endTime,proto3" json:"endTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *DeleteScheduleRequest) Reset()         { *m = DeleteScheduleRequest{} }
func (m *DeleteScheduleRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteScheduleRequest) ProtoMessage()    {}
func (*DeleteScheduleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_199c4d2fc282de6a, []int{6}
}

func (m *DeleteScheduleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteScheduleRequest.Unmarshal(m, b)
}
func (m *DeleteScheduleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteScheduleRequest.Marshal(b, m, deterministic)
}
func (m *DeleteScheduleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteScheduleRequest.Merge(m, src)
}
func (m *DeleteScheduleRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteScheduleRequest.Size(m)
}
func (m *DeleteScheduleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteScheduleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteScheduleRequest proto.InternalMessageInfo

func (m *DeleteScheduleRequest) GetVendor() string {
	if m != nil {
		return m.Vendor
	}
	return ""
}

func (m *DeleteScheduleRequest) GetBrand() string {
	if m != nil {
		return m.Brand
	}
	return ""
}

func (m *DeleteScheduleRequest) GetStartTime() int32 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *DeleteScheduleRequest) GetEndTime() int32 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

type DeleteScheduleResponse struct {
	IsSuccessful         bool     `protobuf:"varint,1,opt,name=isSuccessful,proto3" json:"isSuccessful,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *DeleteScheduleResponse) Reset()         { *m = DeleteScheduleResponse{} }
func (m *DeleteScheduleResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteScheduleResponse) ProtoMessage()    {}
func (*DeleteScheduleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_199c4d2fc282de6a, []int{7}
}

func (m *DeleteScheduleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteScheduleResponse.Unmarshal(m, b)
}
func (m *DeleteScheduleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteScheduleResponse.Marshal(b, m, deterministic)
}
func (m *DeleteScheduleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteScheduleResponse.Merge(m, src)
}
func (m *DeleteScheduleResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteScheduleResponse.Size(m)
}
func (m *DeleteScheduleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteScheduleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteScheduleResponse proto.InternalMessageInfo

func (m *DeleteScheduleResponse) GetIsSuccessful() bool {
	if m != nil {
		return m.IsSuccessful
	}
	return false
}

//Refresh logic
type RefreshScheduleRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RefreshScheduleRequest) Reset()         { *m = RefreshScheduleRequest{} }
func (m *RefreshScheduleRequest) String() string { return proto.CompactTextString(m) }
func (*RefreshScheduleRequest) ProtoMessage()    {}
func (*RefreshScheduleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_199c4d2fc282de6a, []int{8}
}

func (m *RefreshScheduleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshScheduleRequest.Unmarshal(m, b)
}
func (m *RefreshScheduleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshScheduleRequest.Marshal(b, m, deterministic)
}
func (m *RefreshScheduleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshScheduleRequest.Merge(m, src)
}
func (m *RefreshScheduleRequest) XXX_Size() int {
	return xxx_messageInfo_RefreshScheduleRequest.Size(m)
}
func (m *RefreshScheduleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshScheduleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshScheduleRequest proto.InternalMessageInfo

type RefreshScheduleResponse struct {
	RowFilters           map[string]*RowFilterValue `protobuf:"bytes,1,rep,name=rowFilters,proto3" json:"rowFilters,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-" bson:"-"`
	XXX_unrecognized     []byte                     `json:"-" bson:"-"`
	XXX_sizecache        int32                      `json:"-" bson:"-"`
}

func (m *RefreshScheduleResponse) Reset()         { *m = RefreshScheduleResponse{} }
func (m *RefreshScheduleResponse) String() string { return proto.CompactTextString(m) }
func (*RefreshScheduleResponse) ProtoMessage()    {}
func (*RefreshScheduleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_199c4d2fc282de6a, []int{9}
}

func (m *RefreshScheduleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RefreshScheduleResponse.Unmarshal(m, b)
}
func (m *RefreshScheduleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RefreshScheduleResponse.Marshal(b, m, deterministic)
}
func (m *RefreshScheduleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefreshScheduleResponse.Merge(m, src)
}
func (m *RefreshScheduleResponse) XXX_Size() int {
	return xxx_messageInfo_RefreshScheduleResponse.Size(m)
}
func (m *RefreshScheduleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RefreshScheduleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RefreshScheduleResponse proto.InternalMessageInfo

func (m *RefreshScheduleResponse) GetRowFilters() map[string]*RowFilterValue {
	if m != nil {
		return m.RowFilters
	}
	return nil
}

//Helper Messages
type PrimePages struct {
	PageName             string   `protobuf:"bytes,1,opt,name=pageName,proto3" json:"pageName,omitempty"`
	PageEndpoint         string   `protobuf:"bytes,2,opt,name=pageEndpoint,proto3" json:"pageEndpoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *PrimePages) Reset()         { *m = PrimePages{} }
func (m *PrimePages) String() string { return proto.CompactTextString(m) }
func (*PrimePages) ProtoMessage()    {}
func (*PrimePages) Descriptor() ([]byte, []int) {
	return fileDescriptor_199c4d2fc282de6a, []int{10}
}

func (m *PrimePages) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimePages.Unmarshal(m, b)
}
func (m *PrimePages) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimePages.Marshal(b, m, deterministic)
}
func (m *PrimePages) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimePages.Merge(m, src)
}
func (m *PrimePages) XXX_Size() int {
	return xxx_messageInfo_PrimePages.Size(m)
}
func (m *PrimePages) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimePages.DiscardUnknown(m)
}

var xxx_messageInfo_PrimePages proto.InternalMessageInfo

func (m *PrimePages) GetPageName() string {
	if m != nil {
		return m.PageName
	}
	return ""
}

func (m *PrimePages) GetPageEndpoint() string {
	if m != nil {
		return m.PageEndpoint
	}
	return ""
}

type HelperPage struct {
	CarouselEndpoint     string   `protobuf:"bytes,1,opt,name=carouselEndpoint,proto3" json:"carouselEndpoint,omitempty"`
	RowContentEndpoint   []string `protobuf:"bytes,2,rep,name=rowContentEndpoint,proto3" json:"rowContentEndpoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *HelperPage) Reset()         { *m = HelperPage{} }
func (m *HelperPage) String() string { return proto.CompactTextString(m) }
func (*HelperPage) ProtoMessage()    {}
func (*HelperPage) Descriptor() ([]byte, []int) {
	return fileDescriptor_199c4d2fc282de6a, []int{11}
}

func (m *HelperPage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelperPage.Unmarshal(m, b)
}
func (m *HelperPage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelperPage.Marshal(b, m, deterministic)
}
func (m *HelperPage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelperPage.Merge(m, src)
}
func (m *HelperPage) XXX_Size() int {
	return xxx_messageInfo_HelperPage.Size(m)
}
func (m *HelperPage) XXX_DiscardUnknown() {
	xxx_messageInfo_HelperPage.DiscardUnknown(m)
}

var xxx_messageInfo_HelperPage proto.InternalMessageInfo

func (m *HelperPage) GetCarouselEndpoint() string {
	if m != nil {
		return m.CarouselEndpoint
	}
	return ""
}

func (m *HelperPage) GetRowContentEndpoint() []string {
	if m != nil {
		return m.RowContentEndpoint
	}
	return nil
}

type HelperCarosuel struct {
	ImageUrl             string   `protobuf:"bytes,1,opt,name=imageUrl,proto3" json:"imageUrl,omitempty"`
	Target               string   `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	PackageName          string   `protobuf:"bytes,4,opt,name=packageName,proto3" json:"packageName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *HelperCarosuel) Reset()         { *m = HelperCarosuel{} }
func (m *HelperCarosuel) String() string { return proto.CompactTextString(m) }
func (*HelperCarosuel) ProtoMessage()    {}
func (*HelperCarosuel) Descriptor() ([]byte, []int) {
	return fileDescriptor_199c4d2fc282de6a, []int{12}
}

func (m *HelperCarosuel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelperCarosuel.Unmarshal(m, b)
}
func (m *HelperCarosuel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelperCarosuel.Marshal(b, m, deterministic)
}
func (m *HelperCarosuel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelperCarosuel.Merge(m, src)
}
func (m *HelperCarosuel) XXX_Size() int {
	return xxx_messageInfo_HelperCarosuel.Size(m)
}
func (m *HelperCarosuel) XXX_DiscardUnknown() {
	xxx_messageInfo_HelperCarosuel.DiscardUnknown(m)
}

var xxx_messageInfo_HelperCarosuel proto.InternalMessageInfo

func (m *HelperCarosuel) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

func (m *HelperCarosuel) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *HelperCarosuel) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *HelperCarosuel) GetPackageName() string {
	if m != nil {
		return m.PackageName
	}
	return ""
}

type HelperContentTile struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Portrait             []string `protobuf:"bytes,2,rep,name=portrait,proto3" json:"portrait,omitempty"`
	Poster               []string `protobuf:"bytes,3,rep,name=poster,proto3" json:"poster,omitempty"`
	ContentId            string   `protobuf:"bytes,4,opt,name=contentId,proto3" json:"contentId,omitempty"`
	IsDetailPage         bool     `protobuf:"varint,5,opt,name=isDetailPage,proto3" json:"isDetailPage,omitempty"`
	Target               []string `protobuf:"bytes,6,rep,name=target,proto3" json:"target,omitempty"`
	PackageName          string   `protobuf:"bytes,7,opt,name=packageName,proto3" json:"packageName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-" bson:"-"`
	XXX_unrecognized     []byte   `json:"-" bson:"-"`
	XXX_sizecache        int32    `json:"-" bson:"-"`
}

func (m *HelperContentTile) Reset()         { *m = HelperContentTile{} }
func (m *HelperContentTile) String() string { return proto.CompactTextString(m) }
func (*HelperContentTile) ProtoMessage()    {}
func (*HelperContentTile) Descriptor() ([]byte, []int) {
	return fileDescriptor_199c4d2fc282de6a, []int{13}
}

func (m *HelperContentTile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelperContentTile.Unmarshal(m, b)
}
func (m *HelperContentTile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelperContentTile.Marshal(b, m, deterministic)
}
func (m *HelperContentTile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelperContentTile.Merge(m, src)
}
func (m *HelperContentTile) XXX_Size() int {
	return xxx_messageInfo_HelperContentTile.Size(m)
}
func (m *HelperContentTile) XXX_DiscardUnknown() {
	xxx_messageInfo_HelperContentTile.DiscardUnknown(m)
}

var xxx_messageInfo_HelperContentTile proto.InternalMessageInfo

func (m *HelperContentTile) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *HelperContentTile) GetPortrait() []string {
	if m != nil {
		return m.Portrait
	}
	return nil
}

func (m *HelperContentTile) GetPoster() []string {
	if m != nil {
		return m.Poster
	}
	return nil
}

func (m *HelperContentTile) GetContentId() string {
	if m != nil {
		return m.ContentId
	}
	return ""
}

func (m *HelperContentTile) GetIsDetailPage() bool {
	if m != nil {
		return m.IsDetailPage
	}
	return false
}

func (m *HelperContentTile) GetTarget() []string {
	if m != nil {
		return m.Target
	}
	return nil
}

func (m *HelperContentTile) GetPackageName() string {
	if m != nil {
		return m.PackageName
	}
	return ""
}

type HelperRow struct {
	RowName              string               `protobuf:"bytes,1,opt,name=rowName,proto3" json:"rowName,omitempty"`
	Rowlayout            RowLayout            `protobuf:"varint,2,opt,name=rowlayout,proto3,enum=SchedularService.RowLayout" json:"rowlayout,omitempty"`
	RowBaseUrl           string               `protobuf:"bytes,3,opt,name=rowBaseUrl,proto3" json:"rowBaseUrl,omitempty"`
	ContentTile          []*HelperContentTile `protobuf:"bytes,4,rep,name=contentTile,proto3" json:"contentTile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-" bson:"-"`
	XXX_unrecognized     []byte               `json:"-" bson:"-"`
	XXX_sizecache        int32                `json:"-" bson:"-"`
}

func (m *HelperRow) Reset()         { *m = HelperRow{} }
func (m *HelperRow) String() string { return proto.CompactTextString(m) }
func (*HelperRow) ProtoMessage()    {}
func (*HelperRow) Descriptor() ([]byte, []int) {
	return fileDescriptor_199c4d2fc282de6a, []int{14}
}

func (m *HelperRow) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelperRow.Unmarshal(m, b)
}
func (m *HelperRow) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelperRow.Marshal(b, m, deterministic)
}
func (m *HelperRow) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelperRow.Merge(m, src)
}
func (m *HelperRow) XXX_Size() int {
	return xxx_messageInfo_HelperRow.Size(m)
}
func (m *HelperRow) XXX_DiscardUnknown() {
	xxx_messageInfo_HelperRow.DiscardUnknown(m)
}

var xxx_messageInfo_HelperRow proto.InternalMessageInfo

func (m *HelperRow) GetRowName() string {
	if m != nil {
		return m.RowName
	}
	return ""
}

func (m *HelperRow) GetRowlayout() RowLayout {
	if m != nil {
		return m.Rowlayout
	}
	return RowLayout_Landscape
}

func (m *HelperRow) GetRowBaseUrl() string {
	if m != nil {
		return m.RowBaseUrl
	}
	return ""
}

func (m *HelperRow) GetContentTile() []*HelperContentTile {
	if m != nil {
		return m.ContentTile
	}
	return nil
}

func init() {
	proto.RegisterEnum("SchedularService.RowType", RowType_name, RowType_value)
	proto.RegisterEnum("SchedularService.RowLayout", RowLayout_name, RowLayout_value)
	proto.RegisterType((*Schedule)(nil), "SchedularService.Schedule")
	proto.RegisterType((*Page)(nil), "SchedularService.Page")
	proto.RegisterType((*Carousel)(nil), "SchedularService.Carousel")
	proto.RegisterType((*Row)(nil), "SchedularService.Row")
	proto.RegisterMapType((map[string]*RowFilterValue)(nil), "SchedularService.Row.RowFiltersEntry")
	proto.RegisterMapType((map[string]int32)(nil), "SchedularService.Row.RowSortEntry")
	proto.RegisterType((*RowFilterValue)(nil), "SchedularService.RowFilterValue")
	proto.RegisterType((*GetScheduleRequest)(nil), "SchedularService.GetScheduleRequest")
	proto.RegisterType((*DeleteScheduleRequest)(nil), "SchedularService.DeleteScheduleRequest")
	proto.RegisterType((*DeleteScheduleResponse)(nil), "SchedularService.DeleteScheduleResponse")
	proto.RegisterType((*RefreshScheduleRequest)(nil), "SchedularService.RefreshScheduleRequest")
	proto.RegisterType((*RefreshScheduleResponse)(nil), "SchedularService.RefreshScheduleResponse")
	proto.RegisterMapType((map[string]*RowFilterValue)(nil), "SchedularService.RefreshScheduleResponse.RowFiltersEntry")
	proto.RegisterType((*PrimePages)(nil), "SchedularService.PrimePages")
	proto.RegisterType((*HelperPage)(nil), "SchedularService.HelperPage")
	proto.RegisterType((*HelperCarosuel)(nil), "SchedularService.HelperCarosuel")
	proto.RegisterType((*HelperContentTile)(nil), "SchedularService.HelperContentTile")
	proto.RegisterType((*HelperRow)(nil), "SchedularService.HelperRow")
}

func init() { proto.RegisterFile("SchedularService.proto", fileDescriptor_199c4d2fc282de6a) }

var fileDescriptor_199c4d2fc282de6a = []byte{
	// 1135 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x56, 0x5f, 0x6f, 0xe3, 0x44,
	0x10, 0x3f, 0xe7, 0x4f, 0x9b, 0x4c, 0x4a, 0xea, 0xae, 0xda, 0x9e, 0xc9, 0x9d, 0x20, 0x32, 0xa0,
	0x0b, 0x11, 0x4a, 0x50, 0x4e, 0x3a, 0x5d, 0xab, 0x7b, 0x80, 0x6b, 0x0b, 0x54, 0xaa, 0x50, 0xe5,
	0xf6, 0x90, 0x78, 0x42, 0x5b, 0x7b, 0x9a, 0x9a, 0x73, 0xbc, 0xbe, 0xf5, 0xba, 0x21, 0x12, 0x08,
	0x09, 0xbe, 0x01, 0x7c, 0x12, 0x3e, 0x05, 0xcf, 0x08, 0xf1, 0xc0, 0x3b, 0xaf, 0x7c, 0x07, 0xb4,
	0xbb, 0x76, 0x62, 0xc7, 0xb9, 0xde, 0xf1, 0x4f, 0xf7, 0x10, 0xc9, 0x33, 0xfb, 0x9b, 0xdf, 0xce,
	0xcc, 0x4e, 0x7e, 0xbb, 0xb0, 0x7b, 0xe6, 0x5e, 0xa1, 0x97, 0x04, 0x94, 0x9f, 0x21, 0xbf, 0xf6,
	0x5d, 0x1c, 0x44, 0x9c, 0x09, 0x46, 0xcc, 0x65, 0x7f, 0xe7, 0xcd, 0x31, 0x63, 0xe3, 0x00, 0x87,
	0x6a, 0xfd, 0x22, 0xb9, 0x1c, 0x0a, 0x7f, 0x82, 0xb1, 0xa0, 0x93, 0x48, 0x87, 0x74, 0xee, 0xa6,
	0x00, 0x1a, 0xf9, 0x43, 0x1a, 0x86, 0x4c, 0x50, 0xe1, 0xb3, 0x30, 0xd6, 0xab, 0xf6, 0x0f, 0x15,
	0x68, 0xa4, 0x9c, 0x48, 0xb6, 0xa1, 0x7e, 0xc1, 0x69, 0xe8, 0x59, 0x46, 0xd7, 0xe8, 0x35, 0x1d,
	0x6d, 0x90, 0x5d, 0x58, 0xbb, 0xc6, 0xd0, 0x63, 0xdc, 0xaa, 0x28, 0x77, 0x6a, 0x91, 0xbb, 0xd0,
	0x8c, 0x05, 0xe5, 0xe2, 0xdc, 0x9f, 0xa0, 0x55, 0xed, 0x1a, 0xbd, 0xba, 0xb3, 0x70, 0x10, 0x0b,
	0xd6, 0x31, 0xf4, 0xd4, 0x5a, 0x4d, 0xad, 0x65, 0x26, 0x79, 0x0f, 0xea, 0x11, 0x1d, 0x63, 0x6c,
	0xad, 0x75, 0xab, 0xbd, 0xd6, 0x68, 0x77, 0x50, 0xaa, 0xf5, 0x94, 0x8e, 0xd1, 0xd1, 0x20, 0xf2,
	0x10, 0x9a, 0x2e, 0x47, 0x2a, 0xd0, 0xfb, 0x50, 0x58, 0xeb, 0x5d, 0xa3, 0xd7, 0x1a, 0x75, 0x06,
	0xba, 0xa4, 0x41, 0x56, 0xf3, 0xe0, 0x3c, 0xab, 0xd9, 0x59, 0x80, 0x65, 0x64, 0x12, 0x79, 0x69,
	0x64, 0xe3, 0xc5, 0x91, 0x73, 0xb0, 0xfd, 0x53, 0x05, 0x6a, 0x32, 0x07, 0xd2, 0x81, 0x86, 0xcc,
	0xe2, 0x53, 0x3a, 0xc1, 0xb4, 0x27, 0x73, 0x5b, 0x96, 0x2f, 0xbf, 0x8f, 0x43, 0x0f, 0xbf, 0x52,
	0x9d, 0xa9, 0x3b, 0x0b, 0x47, 0x16, 0x79, 0xc2, 0xc6, 0x4c, 0xf5, 0x26, 0x8d, 0x94, 0x36, 0xb9,
	0x07, 0x55, 0xce, 0xa6, 0x56, 0x4d, 0x95, 0xbf, 0x53, 0x2e, 0xdf, 0x61, 0x53, 0x47, 0x22, 0xc8,
	0x03, 0x68, 0xb8, 0x94, 0xb3, 0x24, 0xc6, 0xc0, 0xaa, 0x2b, 0x74, 0xa7, 0x8c, 0x3e, 0x48, 0x11,
	0xce, 0x1c, 0xfb, 0x4a, 0x7a, 0x76, 0x0d, 0x8d, 0x2c, 0x13, 0x39, 0x31, 0x82, 0xf2, 0x31, 0x8a,
	0xb4, 0x69, 0xa9, 0x45, 0xba, 0xd0, 0x8a, 0xa8, 0xfb, 0x34, 0xeb, 0xa8, 0x1e, 0xa7, 0xbc, 0x4b,
	0xb6, 0xcd, 0x9f, 0xd0, 0x31, 0x3e, 0xe1, 0x41, 0xd6, 0xb6, 0xcc, 0x96, 0xd3, 0x29, 0x7c, 0x11,
	0xe8, 0x79, 0x6a, 0x3a, 0xda, 0xb0, 0xff, 0xac, 0x42, 0xd5, 0x61, 0x53, 0xb2, 0x07, 0x4d, 0xce,
	0xa6, 0x01, 0x9d, 0xb1, 0x44, 0x6f, 0xdb, 0x1e, 0xdd, 0x59, 0xd9, 0xda, 0x13, 0x05, 0x71, 0x16,
	0x68, 0x39, 0xaa, 0x9c, 0x4d, 0x73, 0x29, 0x65, 0xa6, 0x4c, 0x87, 0xb3, 0xa9, 0x3e, 0x62, 0x3d,
	0xe1, 0x73, 0x9b, 0x1c, 0x01, 0x70, 0x36, 0xfd, 0xc8, 0x0f, 0x04, 0xf2, 0x38, 0x3d, 0xcc, 0x77,
	0x56, 0xee, 0x28, 0x7f, 0x29, 0xee, 0x28, 0x14, 0x7c, 0xe6, 0xe4, 0x02, 0xc9, 0x23, 0xb5, 0xf9,
	0x19, 0xe3, 0x22, 0x3d, 0x62, 0xfb, 0xb9, 0x1c, 0x12, 0xa4, 0x09, 0xb2, 0x10, 0xf2, 0x86, 0x4a,
	0xe2, 0xdc, 0x0f, 0xf0, 0xd8, 0xd3, 0x7f, 0xa8, 0xa6, 0x93, 0xf3, 0x90, 0xfb, 0x8a, 0xfd, 0x7c,
	0x16, 0xa1, 0x9a, 0x83, 0xf6, 0xe8, 0xf5, 0x95, 0xec, 0x12, 0xe0, 0x64, 0xc8, 0xce, 0x17, 0xb0,
	0xb9, 0x94, 0x31, 0x31, 0xa1, 0xfa, 0x14, 0x67, 0xe9, 0x71, 0xca, 0x4f, 0xf2, 0x00, 0xea, 0xd7,
	0x34, 0x48, 0x74, 0xcb, 0x5a, 0xa3, 0xee, 0x4a, 0x5e, 0xcd, 0xf1, 0x99, 0xc4, 0x39, 0x1a, 0xbe,
	0x5f, 0x79, 0x68, 0x74, 0xf6, 0x61, 0x23, 0x5f, 0xce, 0x0a, 0xf6, 0xed, 0x3c, 0xfb, 0x56, 0x2e,
	0xd6, 0xee, 0x41, 0xbb, 0x48, 0xac, 0xf4, 0x49, 0x7e, 0xc4, 0x96, 0xa1, 0xea, 0x4f, 0x2d, 0xfb,
	0x31, 0x90, 0x8f, 0x51, 0x64, 0xe2, 0xe6, 0xe0, 0xb3, 0x04, 0x63, 0x91, 0x53, 0x33, 0xa3, 0xa0,
	0x66, 0x73, 0xed, 0xab, 0xe4, 0xb4, 0xcf, 0xfe, 0x06, 0x76, 0x0e, 0x31, 0x40, 0x81, 0xff, 0x8a,
	0xe6, 0x9f, 0x4a, 0xa5, 0xfd, 0x08, 0x76, 0x97, 0xb7, 0x8f, 0x23, 0x16, 0xc6, 0x48, 0x6c, 0xd8,
	0xf0, 0xe3, 0xb3, 0xc4, 0x75, 0x31, 0x8e, 0x2f, 0x93, 0x40, 0x65, 0xd1, 0x70, 0x0a, 0x3e, 0xdb,
	0x82, 0x5d, 0x07, 0x2f, 0x39, 0xc6, 0x57, 0x4b, 0xd9, 0xdb, 0xbf, 0x19, 0x70, 0xbb, 0xb4, 0x94,
	0x32, 0x7f, 0x5e, 0x98, 0x6b, 0x43, 0xcd, 0xe4, 0xde, 0x8a, 0xd3, 0x5d, 0x1d, 0x7e, 0xd3, 0xac,
	0xff, 0xef, 0x83, 0x65, 0x9f, 0x00, 0x9c, 0x72, 0x7f, 0x82, 0xa7, 0xea, 0xea, 0xb8, 0x49, 0xbd,
	0x6d, 0xd8, 0x90, 0xdf, 0x47, 0xa1, 0x17, 0x31, 0x3f, 0x14, 0xe9, 0x71, 0x15, 0x7c, 0xf6, 0x15,
	0xc0, 0x27, 0x18, 0x44, 0xc8, 0xd5, 0x5d, 0xd0, 0x07, 0x33, 0x13, 0xd8, 0x79, 0x94, 0x66, 0x2d,
	0xf9, 0xc9, 0x00, 0x08, 0x67, 0xd3, 0x03, 0x16, 0x0a, 0x0c, 0x45, 0x6e, 0x0f, 0x39, 0x9e, 0x2b,
	0x56, 0xec, 0xaf, 0xa1, 0xad, 0x77, 0x92, 0x12, 0x1a, 0x27, 0x18, 0x14, 0x84, 0xd0, 0x58, 0x12,
	0xc2, 0x85, 0xbc, 0x56, 0x0a, 0xf2, 0x3a, 0x17, 0xc8, 0x6a, 0x4e, 0x20, 0x97, 0x45, 0xb7, 0x56,
	0x12, 0x5d, 0xfb, 0x77, 0x03, 0xb6, 0xd2, 0xed, 0x75, 0x5e, 0x52, 0x3d, 0x16, 0x6c, 0x46, 0x9e,
	0x4d, 0xf6, 0x94, 0x71, 0xc1, 0xa9, 0x9f, 0xd5, 0x33, 0xb7, 0x65, 0x5e, 0x11, 0x8b, 0x05, 0x72,
	0xab, 0xaa, 0xff, 0x88, 0xda, 0x92, 0xd3, 0xef, 0x6a, 0xe2, 0x63, 0x2f, 0xdd, 0x7f, 0xe1, 0xd0,
	0x93, 0x7c, 0x88, 0x82, 0xfa, 0x81, 0xec, 0xb3, 0x55, 0xcf, 0x26, 0x79, 0xe1, 0xcb, 0x55, 0xac,
	0x25, 0xee, 0x39, 0x17, 0xca, 0x7a, 0xb9, 0xb6, 0x9f, 0x0d, 0x68, 0xea, 0xda, 0xe4, 0x25, 0x91,
	0x53, 0x7a, 0xa3, 0xa8, 0xf4, 0x85, 0xeb, 0xa3, 0xf2, 0xb7, 0xae, 0x0f, 0xad, 0xc1, 0x8f, 0x69,
	0x9c, 0xbb, 0xb5, 0x72, 0x1e, 0x72, 0x04, 0x2d, 0x77, 0xd1, 0xd7, 0xf4, 0xa6, 0x78, 0xab, 0x4c,
	0x5e, 0x3a, 0x02, 0x27, 0x1f, 0xd7, 0xdf, 0x83, 0xf5, 0x54, 0xa9, 0xc9, 0x6b, 0xd0, 0x3c, 0xf2,
	0x7c, 0xc1, 0xb8, 0x4f, 0x03, 0xf3, 0x16, 0x21, 0xd0, 0x76, 0xd0, 0x65, 0x93, 0x09, 0x86, 0x9e,
	0x7a, 0xdc, 0x99, 0x06, 0x69, 0xc1, 0xfa, 0xe1, 0x2c, 0xa4, 0x13, 0xdf, 0x35, 0x2b, 0xfd, 0x0f,
	0xa0, 0x39, 0xcf, 0x5c, 0x06, 0x9f, 0xd0, 0xd0, 0x8b, 0x5d, 0x1a, 0xa1, 0x79, 0x8b, 0x6c, 0x40,
	0xe3, 0x34, 0x3d, 0x40, 0xd3, 0x20, 0x00, 0x6b, 0x67, 0xcf, 0x12, 0xca, 0xd1, 0xac, 0xca, 0xef,
	0x03, 0x9f, 0xbb, 0x01, 0x9a, 0xb5, 0xd1, 0x2f, 0x35, 0x28, 0x3d, 0x3d, 0x89, 0x07, 0xed, 0x03,
	0xf5, 0x72, 0x98, 0x3f, 0x20, 0x57, 0x3c, 0x4f, 0xb2, 0xb5, 0xce, 0x0d, 0x6b, 0x76, 0xe7, 0xbb,
	0x5f, 0xff, 0xf8, 0xb1, 0xb2, 0x6d, 0x6f, 0x0e, 0xdd, 0x02, 0xe1, 0xbe, 0xd1, 0x27, 0x5f, 0x42,
	0x2b, 0x27, 0xe3, 0xe4, 0xed, 0x32, 0x4d, 0x59, 0xe5, 0x6f, 0xdc, 0xec, 0xb6, 0xda, 0x6c, 0xcb,
	0xde, 0x18, 0x8e, 0x17, 0x81, 0xfb, 0x46, 0xff, 0x7d, 0x43, 0x56, 0xf4, 0x44, 0xbd, 0x68, 0xfe,
	0xc3, 0x8a, 0x92, 0x02, 0xa1, 0xac, 0xe8, 0x5b, 0x68, 0x17, 0x55, 0x9d, 0xdc, 0x2b, 0x33, 0xad,
	0xbc, 0x76, 0x3a, 0xbd, 0x17, 0x03, 0xb5, 0x0e, 0xe7, 0x12, 0xf0, 0x0a, 0x00, 0x99, 0xc0, 0xf7,
	0x06, 0x6c, 0x2e, 0xe9, 0x37, 0xe9, 0xbd, 0x84, 0xc4, 0xeb, 0x1c, 0xde, 0x7d, 0xe9, 0xcb, 0xc0,
	0xbe, 0xa3, 0x92, 0xd8, 0xb1, 0xcd, 0x21, 0x2f, 0x22, 0xf6, 0x8d, 0xfe, 0xc5, 0x9a, 0x7a, 0x50,
	0xde, 0xff, 0x2b, 0x00, 0x00, 0xff, 0xff, 0xc1, 0xa7, 0xfb, 0x33, 0xec, 0x0c, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SchedularServiceClient is the client API for SchedularService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SchedularServiceClient interface {
	//Schedular CRUD
	CreateSchedule(ctx context.Context, in *Schedule, opts ...grpc.CallOption) (*Schedule, error)
	GetSchedule(ctx context.Context, in *GetScheduleRequest, opts ...grpc.CallOption) (SchedularService_GetScheduleClient, error)
	UpdateSchedule(ctx context.Context, in *Schedule, opts ...grpc.CallOption) (*Schedule, error)
	DeleteSchedule(ctx context.Context, in *DeleteScheduleRequest, opts ...grpc.CallOption) (*DeleteScheduleResponse, error)
	//Refresh manupilation
	RefreshSchedule(ctx context.Context, in *RefreshScheduleRequest, opts ...grpc.CallOption) (*RefreshScheduleResponse, error)
}

type schedularServiceClient struct {
	cc *grpc.ClientConn
}

func NewSchedularServiceClient(cc *grpc.ClientConn) SchedularServiceClient {
	return &schedularServiceClient{cc}
}

func (c *schedularServiceClient) CreateSchedule(ctx context.Context, in *Schedule, opts ...grpc.CallOption) (*Schedule, error) {
	out := new(Schedule)
	err := c.cc.Invoke(ctx, "/SchedularService.SchedularService/CreateSchedule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedularServiceClient) GetSchedule(ctx context.Context, in *GetScheduleRequest, opts ...grpc.CallOption) (SchedularService_GetScheduleClient, error) {
	stream, err := c.cc.NewStream(ctx, &_SchedularService_serviceDesc.Streams[0], "/SchedularService.SchedularService/GetSchedule", opts...)
	if err != nil {
		return nil, err
	}
	x := &schedularServiceGetScheduleClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SchedularService_GetScheduleClient interface {
	Recv() (*Schedule, error)
	grpc.ClientStream
}

type schedularServiceGetScheduleClient struct {
	grpc.ClientStream
}

func (x *schedularServiceGetScheduleClient) Recv() (*Schedule, error) {
	m := new(Schedule)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *schedularServiceClient) UpdateSchedule(ctx context.Context, in *Schedule, opts ...grpc.CallOption) (*Schedule, error) {
	out := new(Schedule)
	err := c.cc.Invoke(ctx, "/SchedularService.SchedularService/UpdateSchedule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedularServiceClient) DeleteSchedule(ctx context.Context, in *DeleteScheduleRequest, opts ...grpc.CallOption) (*DeleteScheduleResponse, error) {
	out := new(DeleteScheduleResponse)
	err := c.cc.Invoke(ctx, "/SchedularService.SchedularService/DeleteSchedule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *schedularServiceClient) RefreshSchedule(ctx context.Context, in *RefreshScheduleRequest, opts ...grpc.CallOption) (*RefreshScheduleResponse, error) {
	out := new(RefreshScheduleResponse)
	err := c.cc.Invoke(ctx, "/SchedularService.SchedularService/RefreshSchedule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SchedularServiceServer is the server API for SchedularService service.
type SchedularServiceServer interface {
	//Schedular CRUD
	CreateSchedule(context.Context, *Schedule) (*Schedule, error)
	GetSchedule(*GetScheduleRequest, SchedularService_GetScheduleServer) error
	UpdateSchedule(context.Context, *Schedule) (*Schedule, error)
	DeleteSchedule(context.Context, *DeleteScheduleRequest) (*DeleteScheduleResponse, error)
	//Refresh manupilation
	RefreshSchedule(context.Context, *RefreshScheduleRequest) (*RefreshScheduleResponse, error)
}

// UnimplementedSchedularServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSchedularServiceServer struct {
}

func (*UnimplementedSchedularServiceServer) CreateSchedule(ctx context.Context, req *Schedule) (*Schedule, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSchedule not implemented")
}
func (*UnimplementedSchedularServiceServer) GetSchedule(req *GetScheduleRequest, srv SchedularService_GetScheduleServer) error {
	return status.Errorf(codes.Unimplemented, "method GetSchedule not implemented")
}
func (*UnimplementedSchedularServiceServer) UpdateSchedule(ctx context.Context, req *Schedule) (*Schedule, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSchedule not implemented")
}
func (*UnimplementedSchedularServiceServer) DeleteSchedule(ctx context.Context, req *DeleteScheduleRequest) (*DeleteScheduleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSchedule not implemented")
}
func (*UnimplementedSchedularServiceServer) RefreshSchedule(ctx context.Context, req *RefreshScheduleRequest) (*RefreshScheduleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshSchedule not implemented")
}

func RegisterSchedularServiceServer(s *grpc.Server, srv SchedularServiceServer) {
	s.RegisterService(&_SchedularService_serviceDesc, srv)
}

func _SchedularService_CreateSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Schedule)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedularServiceServer).CreateSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SchedularService.SchedularService/CreateSchedule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedularServiceServer).CreateSchedule(ctx, req.(*Schedule))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedularService_GetSchedule_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetScheduleRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SchedularServiceServer).GetSchedule(m, &schedularServiceGetScheduleServer{stream})
}

type SchedularService_GetScheduleServer interface {
	Send(*Schedule) error
	grpc.ServerStream
}

type schedularServiceGetScheduleServer struct {
	grpc.ServerStream
}

func (x *schedularServiceGetScheduleServer) Send(m *Schedule) error {
	return x.ServerStream.SendMsg(m)
}

func _SchedularService_UpdateSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Schedule)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedularServiceServer).UpdateSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SchedularService.SchedularService/UpdateSchedule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedularServiceServer).UpdateSchedule(ctx, req.(*Schedule))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedularService_DeleteSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedularServiceServer).DeleteSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SchedularService.SchedularService/DeleteSchedule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedularServiceServer).DeleteSchedule(ctx, req.(*DeleteScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SchedularService_RefreshSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedularServiceServer).RefreshSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/SchedularService.SchedularService/RefreshSchedule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedularServiceServer).RefreshSchedule(ctx, req.(*RefreshScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SchedularService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "SchedularService.SchedularService",
	HandlerType: (*SchedularServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSchedule",
			Handler:    _SchedularService_CreateSchedule_Handler,
		},
		{
			MethodName: "UpdateSchedule",
			Handler:    _SchedularService_UpdateSchedule_Handler,
		},
		{
			MethodName: "DeleteSchedule",
			Handler:    _SchedularService_DeleteSchedule_Handler,
		},
		{
			MethodName: "RefreshSchedule",
			Handler:    _SchedularService_RefreshSchedule_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetSchedule",
			Handler:       _SchedularService_GetSchedule_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "SchedularService.proto",
}
